nginx:
    image:aloha1003/nginx
    ports:
    - "10081:80"
  volumes:
    - .:/usr/share/nginx/html:ro
    links:
    # 連結 redis 與 mysql 環境
    - redis
    - mysql
php:
    image:aloha1003/php
redis:
    image:aloha1003/redis
    - "6379:6379"
    volumes:
    # 將實體機器的資料庫 data 掛載到 docker 裡面
    - "/usr/local/var/db/redis:/data"
mysql:
  image: aloha1003/mysql
  ports:
    - "3306:3306"
  volumes:
    - "/etc/mysql:/var/lib/mysql"
  working_dir:
      - "/Applications/AMPPS/var"
  environment:
    # 定義 mysql 的 root 密碼
    MYSQL_ROOT_PASSWORD: "root"
gulp:
  image: aloha1003/gulp
